# This is a basic workflow to help you get started with Actions

name: Generate diffs

# Controls when the action will run. 
on:
  # trigger automatically when a new release is published
  release:
    types: [released]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "update"
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        #https://github.com/marketplace/actions/get-github-release-json
      - name: Get releases
        uses: ctrlaltdev/get-releases-action@latest
        with:
          repo: Mauler125/r5sdk
          token: ${{ secrets.GITHUB_TOKEN }}
          limit: 2
          fields: id,tag_name,assets
          # include_prerelease: false
        #outputs to `releases`
        
      - name: Start SSH session
        uses: luchihoratiu/debug-via-ssh@main
        with:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
